# Generated by Django 5.0.6 on 2024-05-26 11:45

import accounts.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='gfg',
            managers=[
                ('objects', accounts.manager.UserManager()),
            ],
        ),
    ]
